### ISSUE TITLE
Last release lacks APK

### ISSUE THREAD

**Issue by IzzySoft** [alt236/Floating-Info---Android#8]
Just noticed the last release here at Github has no APK attached. Intentionally – or just forgotten? Could you please add it? Thanks in advance!

**Comment by alt236** [comment]
Good catch, I forgot to add it!
It is uploaded now.

**Comment by IzzySoft** [comment]
Thanks a lot! Feel free to point Playstore abstainers [here](https://apt.izzysoft.de/fdroid/index/apk/uk.co.alt236.floatinginfo) then (repo can be used with the F-Droid client). Updates will be pulled automatically from the `releases/` tab here as soon as you've created a new tag – and attached the `.apk` to it :wink:
